version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g aws-sam-cli
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket $S3_BUCKET
artifacts:
  files:
    - packaged.yaml
